# Generated by Django 5.0.4 on 2024-05-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='Phone',
            field=models.CharField(max_length=11),
        ),
    ]
