# Generated by Django 5.0.4 on 2024-05-09 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_alter_author_phone'),
        ('posts', '0002_alter_post_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
